### ISSUE TITLE
Haddock to Latex fails on Data-Text-Internal

### ISSUE THREAD

**Issue by pjljvandelaar** [haskell/text#233] opened 2018-09-04 12:28 UTC
When I run 
` stack haddock --haddock-arguments "--latex"`
on a project that contains Data.Text  (from text 1.2.3.0), I get
```
    haddock: internal error: .stack-work\dist\67675594\doc\html\text\Data-Text-Internal.tex: commitBuffer: invalid argument (invalid character)
```
After which `haddock` stops.

Could this offending character be removed?

Of course, maybe the bug is in haddock: see https://github.com/haskell/haddock/issues/929.

**Comment by hvr** [comment] 2018-09-04 13:28
I couldn't reproduce this with

    cabal new-haddock -w ghc-8.4.3 --haddock-options=--latex

**Comment by hvr** [comment] 2018-09-04 13:34
I've looked at the haddock code-base and it looks like this is a haddock bug that occurs for the corner case of using `--latex` in combination with an inappropriate system locale.

I'm closing this in favor of handling this upstream at haskell/haddock#929

**Closed by hvr** 2018-09-04 13:34 UTC
