### ISSUE TITLE
Illuminating documentation has been banned by Google.

### ISSUE THREAD

**Issue by recursion-ninja** [haskell/text#256] opened 2019-04-11 21:22 UTC
The documentation in the `Data.Data` instances for `Data.Text.Text` has the following link: 

 > [could we get a Data instance for Data.Text.Text?](https://groups.google.com/forum/#!topic/haskell-cafe/tbuxsop-Ul0)

However, as you can see by following the link, the documentation content is not accessible and instead you are presented by a "Banned Content Warning" from Google.

I don't know how or where to find an archived version of this illuminating documentation on the design decision of including the `Data.Data` instance, but I am very interested in reading this content.

Can we get an archived version of the conversation documented someplace stable and under our purview? Perhaps, once the conversation is recovered, we should instead link to a markdown file included in the `text` package instead of the Google Group?

**Comment by hvr** [comment] 2019-04-12 09:54
https://mail.haskell.org/pipermail/haskell-cafe/2010-January/072379.html

**Comment by hvr** [comment] 2019-04-16 16:27
Fixed via #257

**Closed by hvr** 2019-04-16 16:27 UTC
Labels: documentation

**Comment by hvr** [comment] 2019-04-16 16:29
Duplicate of #253
