### ISSUE TITLE
Inconsistent encoding/decoding of Utf8 text

### ISSUE THREAD

**Issue by kalhauge** [haskell/text#220] opened 2018-04-26 00:03 UTC
Thank you for maintaining this fantastic library, 

I have found an inconsistency when encoding and decoding 
"\55296". 

```haskell
> import Data.Text.Encoding
> :set -XOverloadedStrings
> decodeUtf8 (encodeUtf8 "\55296")
"\65533"
```

The bug seems to be system independent and happening in at least version 1.2.2.2.

**Comment by kalhauge** [comment] 2018-04-26 00:13
The bug seems to exist in the range `["\55296" .. "\57343"]`.

**Comment by hvr** [comment] 2018-04-26 13:14
@kalhauge this is not a bug; it works as designed; in fact it's documented behaviour:

> Within this module, many functions construct a Text from one or more Char values. Those functions will substitute Char values that are not valid Unicode scalar values with the replacement character "�" (U+FFFD). Functions that perform this inspection and replacement are documented with the phrase "Performs replacement on invalid scalar values".


the range `["\55296" .. "\57343"]` is exactly the range that does not constitute Unicode scalar values, i.e. surrogate code points.

**Comment by kalhauge** [comment] 2018-04-26 14:45
Uh, I see! Thank you!

However, I use it in a project where losslessness is very important, so I would much rather have `encodeUtf8` throw an error, so I can correctly handle the edge-cases.

Would it make sense to have something like`encodeUtf8With` so that an error is thrown if I try to
encode anything not encodable?

**Comment by Lysxia** [comment] 2022-05-15 19:29
The replacement is actually done by the implicit `Data.Text.pack` inserted by `OverloadedStrings`. So it is not a problem with `encodeUtf8`/`decodeUtf8`.

The fact that `String` does not quite map to `Text` may certainly be surprising, but there doesn't seem to be much the text library can do about it beyond the note "Performs replacement on invalid scalar values." that is already on the doc of `Data.Text.pack` and the surrounding explanation in that module. That is also one more reason to avoid `String` to begin with, at least for untrusted input, which I believe is common advice already.

Therefore I'm closing this issue, but further suggestions to improve the situation are of course welcome.

**Closed by Lysxia** 2022-05-15 19:29 UTC
Labels: question

**Comment by kalhauge** [comment] 2022-05-15 21:23
I have just tested out your hypothesis, and you are completely correct:

```
$ ghci
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Prelude> import Data.Text as T
Prelude T> T.pack "\55296"
"\65533"
```

Thank you for your answer :)
