### ISSUE TITLE
Surprising performance of Text appends with Writer

### ISSUE THREAD

**Issue by tserduke** [haskell/text#165] opened 2016-09-12 18:15 UTC
Appending `Text` with `Writer` seems about 2 times faster than using `append` and 1.5 times faster than `concat`. Here is the [benchmark gist](https://gist.github.com/tserduke/37d2997fe376dcdf62fa1b8442a6a99f).

Time:
append 832.0 ns
concat 519.0 ns
write 321.7 ns

Allocations (measured with [weigh](https://github.com/fpco/weigh)):
append  2,392 bytes
concat 1,536 bytes
write 1,096 bytes

Tested on Ubuntu 14.04 with text-1.2.2.1, GHC 7.10.3 and -O2.

I expected to see `Writer` having similar performance to `append`, but somehow it is much faster.

**Comment by tserduke** [comment] 2016-09-14 09:45
Similar benchmarks for lists, bytestrings and vectors show appends being the fastest and writer being the slowest. So, I guess, text could have 2 times faster appends at least.

**Comment by andrewthad** [comment] 2017-07-19 13:40
Stream fusion is the culprit. If you look at how `append` gets turned into a function that operates on a stream, you'll notice that every call to append ends up building a data type that gets deeper and deeper. For small pieces of text, this is really bad. Things like this get hit the worst:

    "a" <> "b" <> "c" <> "d" <> "e"

The `Writer` version is faster because it blocks rewrite rules from happening (no stream fusion). The fact that `Writer` is faster than `concat` is just weird though.

**Comment by bos** [comment] 2017-08-08 03:38
I was interested enough in this to try reproducing your numbers, but couldn't. I'm using a much newer compiler (8.2.1) in a different environment (OS X on an unplugged laptop), so there are many variables at play to confound things, but:

```
$ dist/build/text-benchmarks/text-benchmarks Concat --regress allocated:time +RTS -T
benchmarking Concat/append
time                 193.6 ns   (190.6 ns .. 196.5 ns)
                     0.998 R²   (0.998 R² .. 0.999 R²)
mean                 184.2 ns   (181.6 ns .. 187.4 ns)
std dev              8.531 ns   (6.792 ns .. 10.71 ns)
allocated:           0.144 R²   (0.112 R² .. 0.185 R²)
  time               5513979.779 (4461724.758 .. 7055603.359)
  y                  492301.895 (428504.961 .. 556261.427)
variance introduced by outliers: 66% (severely inflated)

benchmarking Concat/concat
time                 166.2 ns   (163.9 ns .. 168.7 ns)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 160.9 ns   (159.6 ns .. 162.2 ns)
std dev              3.855 ns   (3.130 ns .. 4.620 ns)
allocated:           0.149 R²   (0.113 R² .. 0.193 R²)
  time               6037036.177 (4927788.705 .. 7690876.116)
  y                  492069.569 (428428.009 .. 562271.320)
variance introduced by outliers: 33% (moderately inflated)

benchmarking Concat/write
time                 192.6 ns   (190.7 ns .. 195.3 ns)
                     0.998 R²   (0.997 R² .. 1.000 R²)
mean                 185.8 ns   (183.4 ns .. 189.6 ns)
std dev              9.203 ns   (6.226 ns .. 14.33 ns)
allocated:           0.151 R²   (0.117 R² .. 0.195 R²)
  time               5939125.201 (4860883.714 .. 7597976.783)
  y                  486381.864 (418172.169 .. 550635.646)
variance introduced by outliers: 68% (severely inflated)
```

(Note: as this transcript suggests, you don't need to use a separate package to measure memory allocation.)

I'll close this as non-reproducible, but you're welcome to reopen if you can find some more conclusive data that this wasn't just a GHC thing.

**Closed by bos** 2017-08-08 03:38 UTC
